import { Manrope } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/toastProvider";
import GoogleProvider from "@/components/googleProvider";
import { AuthProvider } from "@/context/AuthContext";
import { NotificationProvider } from "@/context/NotificationContext";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
});


export const metadata = {
  title: "Creadblaze User",
  description: "Generated by Creadblaze User Dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} `}>
      <body>
        <AuthProvider>
          <NotificationProvider>
            <GoogleProvider>
              <ToastProvider />
              {children}
            </GoogleProvider>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
