import { Manrope, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/toastProvider";
import GoogleProvider from "@/components/googleProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],

});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} `}>
      <body>
        <GoogleProvider>
          <ToastProvider />
          {children}
        </GoogleProvider>
      </body>
    </html>
  );
}
